version: "3.8"

services:
  mongodb:
    image: mongo:4.2
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db

  grasscutter:
    build: .
    restart: always
    ports:
      - "80:80/tcp"
      - "22102:22102/udp"
    volumes:
      - ./config.json:/var/www/config.json
    depends_on:
      - mongodb
    stdin_open: true
    tty: true
volumes:
  data:
